# Generated by Django 5.2.7 on 2026-03-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Novosti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.TextField()),
                ('kratki_opis', models.TextField()),
                ('glavna_slika', models.ImageField(upload_to='novostislike')),
                ('dugi_opis', models.TextField()),
            ],
        ),
    ]
