# Generated by Django 5.2.7 on 2026-03-14 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novosti',
            name='slug',
            field=models.CharField(default='1', max_length=80),
        ),
        migrations.AlterField(
            model_name='novosti',
            name='glavna_slika',
            field=models.ImageField(upload_to='novostislike/glavna'),
        ),
        migrations.CreateModel(
            name='NovostiSlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='novostislike/')),
                ('novost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.novosti')),
            ],
        ),
    ]
