# Generated by Django 5.2.7 on 2026-03-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_novosti_slug_alter_novosti_glavna_slika_novostislike'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natjecanja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_natjecanja', models.DateField()),
                ('vrsta_natjecanja', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='novostislike',
            name='image',
            field=models.ImageField(upload_to='novostislike/ostale'),
        ),
    ]
