# Generated by Django 5.2.7 on 2026-03-15 15:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_natjecanja_alter_novostislike_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='novosti',
            name='datum_objave',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
