# Generated by Django 5.2.7 on 2026-03-15 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_novosti_datum_objave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galerija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='GalerijaSlike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.ImageField(upload_to='galerija/')),
                ('galerija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.galerija')),
            ],
        ),
    ]
